services:
  backend:
    build:
      context: "./backend"
    ports:
      - "3000:3000"
    env_file:
      - "./backend/.env"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database

  frontend:
    build:
      context: "./frontend"
    ports:
      - "80:80"
    env_file:
      - "./frontend/.env"
    depends_on:
      - backend

  database:
    image: postgres:17.2
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
